### ISSUE TITLE
createAuthor returns error, though the record was created in the database.

### ISSUE THREAD

**Issue by ricklang** [juffalow/express-graphql-example#10]
Ran the test case:
mutation {
  createAuthor(author: {
    name: "Kent",
    last_name: "Beck"
  }) {
    id
  }
}

Got the following error. The record actually was created in the database.

{
  "errors": [
    {
      "message": "Cannot read property 'forEach' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createAuthor"
      ]
    }
  ],
  "data": {
    "createAuthor": null
  }
}

**Comment by juffalow** [comment]
Hi, thank you! I will try to fix this asap.

**Comment by juffalow** [comment]
Again, thank you! The mutation required quotes and if you did not provide them, it crashed. Now it is fixed.

**Comment by ricklang** [comment]
It is working now. Thanks.
