### ISSUE TITLE
Mutation for update and delete

### ISSUE THREAD

**Issue by pranatayudha** [juffalow/express-graphql-example#5]
How I can do delete and update data with the mutation? And why query doesnt result data but can insert to the database? Sorry for bad english

**Comment by juffalow** [comment]
Unfortunately there is no option to update or delete the data. I will create a task for it.
And sorry, I don't understand what you mean by "why query doesnt result data but can insert to the database". Can you explain it?

**Comment by pranatayudha** [comment]
I want to see the data that has been inserted into the database. I mean when i run the mutation, i wanna see the JSON result to ensure that the data is actually entered into the database.

**Comment by juffalow** [comment]
It is there. See the mutation to add author:

```
mutation{
  createAuthor(author:{
    name:"Kent",
    last_name:"Beck"
  }) {
    id
  }
}
```

Here you create new author and immediately return his new ID. But of course it can return you also his `name` and `last_name`.

**Comment by juffalow** [comment]
I added mutations for update and delete specific quote ;-)

**Comment by pranatayudha** [comment]
Thanks dude, it's work! I apologize in advance🙏

2018-03-02 20:19 GMT+07:00 Matej Jellus <notifications@github.com>:
